version: '3.8'
services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres-patient:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: patient_user
      POSTGRES_PASSWORD: patient_pass
    ports:
      - "5432:5432"

  postgres-appointment:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: appointment_pass
    ports:
      - "5433:5432"

  postgres-billing:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
    ports:
      - "5434:5432"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # API Gateway
  api-gateway:
    build: ./gateway/api-gateway
    ports:
      - "8080:8080"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8082
      - MEDICAL_RECORDS_SERVICE_URL=http://medical-records-service:8083
      - BILLING_SERVICE_URL=http://billing-service:8084
      - REDIS_URL=redis:6379
    depends_on:
      - redis

  # Core Services
  patient-service:
    build: ./services/patient-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-patient
      - DB_PORT=5432
      - DB_NAME=patient_db
      - DB_USER=patient_user
      - DB_PASSWORD=patient_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis:6379
    depends_on:
      - postgres-patient
      - kafka
      - redis

  appointment-service:
    build: ./services/appointment-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-appointment
      - DB_PORT=5432
      - DB_NAME=appointment_db
      - DB_USER=appointment_user
      - DB_PASSWORD=appointment_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres-appointment
      - kafka

  medical-records-service:
    build: ./services/medical-records-service
    ports:
      - "8083:8083"
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/medical_records?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka

  billing-service:
    build: ./services/billing-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres-billing
      - DB_PORT=5432
      - DB_NAME=billing_db
      - DB_USER=billing_user
      - DB_PASSWORD=billing_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres-billing
      - kafka

  telemedicine-service:
    build: ./services/telemedicine-service
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/telemedicine?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka

  inventory-service:
    build: ./services/inventory-service
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=postgres-patient
      - DB_PORT=5432
      - DB_NAME=patient_db
      - DB_USER=patient_user
      - DB_PASSWORD=patient_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres-patient
      - kafka

  notification-service:
    build: ./services/notification-service
    ports:
      - "8087:8087"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis:6379
    depends_on:
      - kafka
      - redis

  analytics-service:
    build: ./services/analytics-service
    ports:
      - "8088:8088"
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/analytics?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka