services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres-patient:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: patient_user
      POSTGRES_PASSWORD: patient_pass
    ports:
      - "5432:5432"

  postgres-appointment:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: appointment_pass
    ports:
      - "5433:5432"

  postgres-billing:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
    ports:
      - "5434:5432"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # API Gateway
  api-gateway:
    build: ./gateway/api-gateway
    ports:
      - "8080:8080"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8082
    depends_on:
      - redis

  # Core Services (simplified for quick start)
  patient-service:
    build: ./services/patient-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-patient
      - DB_PORT=5432
      - DB_NAME=patient_db
      - DB_USER=patient_user
      - DB_PASSWORD=patient_pass
    depends_on:
      - postgres-patient

  appointment-service:
    build: ./services/appointment-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-appointment
      - DB_PORT=5432
      - DB_NAME=appointment_db
      - DB_USER=appointment_user
      - DB_PASSWORD=appointment_pass
    depends_on:
      - postgres-appointment
