apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-patient-pvc
  namespace: healthcare-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard